version: '3.5'

services:
  nginx:
    ports:
     - ${CODALAB_HTTPS_PORT}:${CODALAB_HTTPS_PORT}
    volumes:
      - ./files/nginx.conf.ssl:/etc/nginx/nginx.conf:ro
      - ${CODALAB_SSL_KEY_FILE}:/opt/ssl/codalab.key
      - ${CODALAB_SSL_CERT_FILE}:/opt/ssl/codalab.crt

  ws-server:
    command: cl-ws-server --port ${CODALAB_WS_PORT} --cert-path ${CODALAB_SSL_CERT_FILE}
    volumes:
      - ${CODALAB_SSL_KEY_FILE}:/opt/ssl/codalab.key
      - ${CODALAB_SSL_CERT_FILE}:/opt/ssl/codalab.crt

    worker:
    command: |
      cl-worker
      --server http://rest-server:${CODALAB_REST_PORT}
      --ws-server ws://ws-server:${CODALAB_WS_PORT}
      --work-dir ${CODALAB_WORKER_DIR}
      --network-prefix ${CODALAB_WORKER_NETWORK_PREFIX}
      --id ${HOSTNAME}
      --verbose
      --use-ssl

  worker2:
    command: |
      cl-worker
      --server http://rest-server:${CODALAB_REST_PORT}
      --ws-server ws://ws-server:${CODALAB_WS_PORT}
      --work-dir ${CODALAB_WORKER_DIR}
      --network-prefix ${CODALAB_WORKER_NETWORK_PREFIX}
      --id ${HOSTNAME}-worker2
      --verbose
      --use-ssl

  worker-preemptible:
    command: |
      cl-worker
      --server http://rest-server:${CODALAB_REST_PORT}
      --ws-server ws://ws-server:${CODALAB_WS_PORT}
      --work-dir ${CODALAB_WORKER_DIR}
      --network-prefix ${CODALAB_WORKER_NETWORK_PREFIX}
      --id ${HOSTNAME}-worker-preemptible
      --verbose
      --preemptible
      --tag preemptible
      --use-ssl

  worker-preemptible2:
    command: |
      cl-worker
      --server http://rest-server:${CODALAB_REST_PORT}
      --ws-server ws://ws-server:${CODALAB_WS_PORT}
      --work-dir ${CODALAB_WORKER_DIR}
      --network-prefix ${CODALAB_WORKER_NETWORK_PREFIX}
      --id ${HOSTNAME}-worker-preemptible2
      --verbose
      --preemptible
      --tag preemptible
      --use-ssl

  worker-shared-file-system:
    command: |
      cl-worker
      --server http://rest-server:${CODALAB_REST_PORT}
      --ws-server ws://ws-server:${CODALAB_WS_PORT}
      --work-dir ${CODALAB_WORKER_DIR}
      --network-prefix ${CODALAB_WORKER_NETWORK_PREFIX}
      --id ${HOSTNAME}
      --shared-file-system
      --verbose
      --use-ssl