name: Test
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [rest-server, worker, frontend]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-
      - run: pip install -r requirements.txt
      - run: echo || python3 codalab_service.py build --pull --version ${VERSION} -s ${SERVICE} $([ -z "${CODALAB_DOCKER_USERNAME}" ] || echo "--push")
        env:
          CODALAB_DOCKER_USERNAME: ${{ secrets.CODALAB_DOCKER_USERNAME }}
          CODALAB_DOCKER_PASSWORD: ${{ secrets.CODALAB_DOCKER_PASSWORD }}
          # Gives us the branch name of the PR if on a pull_request-triggered build,
          # otherwise, "master" if on a push-triggered build
          VERSION: ${{ github.head_ref || 'master' }}
          SERVICE: ${{ matrix.service }}

  test_backend:
    name: Test backend
    runs-on: ubuntu-latest
    #needs: [build]
    strategy:
      matrix:
        test:
          - run
        runtime: [kubernetes]
    steps:
      - name: Clear free space
        run: |
            sudo rm -rf /opt/ghc
            df -h
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-
      - run: pip install -r requirements.txt
      - name: Setup tests
        run: |
          sudo service mysql stop
          python3 codalab_service.py build services --version ${VERSION} --pull
        env:
          VERSION: ${{ github.head_ref || 'master' }}
      - name: Run tests using Docker runtime
        if: matrix.runtime == 'docker'
        run: |
          sh ./tests/test-setup.sh
          python3 codalab_service.py start --services default --version ${VERSION}
          python3 test_runner.py --version ${VERSION} ${TEST}
        env:
          TEST: ${{ matrix.test }}
          VERSION: ${{ github.head_ref || 'master' }}
          CODALAB_LINK_MOUNTS: /tmp
      - uses: actions/setup-go@v3
        if: matrix.runtime == 'kubernetes'
        with:
          go-version: '1.18.1'
      - name: Run tests using Kubernetes runtime
        if: matrix.runtime == 'kubernetes'
        run: |
          sh ./tests/test-setup.sh
          sh ./scripts/local-k8s/setup-ci.sh
          #python3 test_runner.py --version ${VERSION} ${TEST}
          uuid=$(cl run --request-memory 20m "echo")
          echo $uuid
          cl wait $uuid
        env:
          TEST: ${{ matrix.test }}
          VERSION: ${{ github.head_ref || 'master' }}
          CODALAB_LINK_MOUNTS: /tmp
      - name: Save logs
        if: always()
        run: |
          mkdir /tmp/logs
          for c in $(docker ps -a --format="{{.Names}}"); do docker logs $c > /tmp/logs/$c.log 2> /tmp/logs/$c.err.log; done
      - name: Save kubernetes logs
        if: always() && matrix.runtime == 'kubernetes'
        run: |
          kubectl config use-context kind-codalab
          kubectl get pods --output=jsonpath={.items..metadata.name}
          for c in $(kubectl get pods --output=jsonpath={.items..metadata.name}); do echo $c; done
          # for c in $(kubectl get pods --output=jsonpath={.items..metadata.name}); do kubectl logs $c > /tmp/logs/$c.log 2> /tmp/logs/$c.err.log; done
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: logs-test-${{ matrix.runtime }}-${{ matrix.test }}
          path: /tmp/logs
