name: Test
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test_backend:
    name: Test backend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - {name: kill, index: 1}
          - {name: kill, index: 2}
          - {name: kill, index: 3}
          - {name: kill, index: 4}
          - {name: kill, index: 5}
          - {name: kill, index: 6}
          - {name: kill, index: 7}
          - {name: kill, index: 8}
          - {name: kill, index: 9}
          - {name: kill, index: 10}
          - {name: kill, index: 11}
          - {name: kill, index: 12}
          - {name: kill, index: 13}
          - {name: kill, index: 14}
          - {name: kill, index: 15}
          - {name: kill, index: 16}
          - {name: kill, index: 17}
          - {name: kill, index: 18}
          - {name: kill, index: 19}
          - {name: kill, index: 20}
          - {name: kill, index: 21}
          - {name: kill, index: 22}
          - {name: kill, index: 23}
          - {name: kill, index: 24}
          - {name: kill, index: 25}
        runtime: [docker]
    steps:
      - name: Clear free space
        run: |
            sudo rm -rf /opt/ghc
            df -h
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-
      - run: pip install -r requirements.txt
      - name: Setup tests
        run: |
          sudo service mysql stop
          python3 codalab_service.py build services --version ${VERSION} --pull
        env:
          VERSION: ${{ github.head_ref || 'master' }}
      - name: Run tests using Docker runtime
        if: matrix.runtime == 'docker'
        run: |
          sh ./tests/test-setup.sh
          python3 codalab_service.py start --services default --version ${VERSION}
          python3 test_runner.py --version ${VERSION} ${TEST}
        env:
          TEST: ${{ matrix.test.name }}
          VERSION: ${{ github.head_ref || 'master' }}
          CODALAB_LINK_MOUNTS: /tmp
      - name: Save logs
        if: (failure() || cancelled())
        run: |
          mkdir /tmp/logs
          for c in $(docker ps -a --format="{{.Names}}"); do docker logs $c > /tmp/logs/$c.log 2> /tmp/logs/$c.err.log; done
      - name: Upload logs
        if: (failure() || cancelled())
        uses: actions/upload-artifact@v1
        with:
          name: logs-test-docker-${{ matrix.test.name }}-${{ matrix.test.index }}
          path: /tmp/logs