name: Test
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test_backend:
    name: Test backend
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        test:
          - kill kill kill kill kill kill kill kill kill kill kill kill kill kill kill kill kill kill kill kill kill kill kill kill kill
        runtime: [docker]
    steps:
      - name: Clear free space
        run: |
            sudo rm -rf /opt/ghc
            df -h
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-
      - run: pip install -r requirements.txt
      - name: Setup tests
        run: |
          sudo service mysql stop
          python3 codalab_service.py build services --version ${VERSION} --pull
        env:
          VERSION: ${{ github.head_ref || 'master' }}
      - name: Run tests using Docker runtime
        if: matrix.runtime == 'docker'
        run: |
          sh ./tests/test-setup.sh
          python3 codalab_service.py start --services default --version ${VERSION}
          python3 test_runner.py --version ${VERSION} ${TEST}
        env:
          TEST: ${{ matrix.test }}
          VERSION: ${{ github.head_ref || 'master' }}
          CODALAB_LINK_MOUNTS: /tmp
      - name: Save logs
        if: (failure() || cancelled())
        run: |
          mkdir /tmp/logs
          for c in $(docker ps -a --format="{{.Names}}"); do docker logs $c > /tmp/logs/$c.log 2> /tmp/logs/$c.err.log; done
      - name: Upload logs
        if: (failure() || cancelled())
        uses: actions/upload-artifact@v1
        with:
          name: logs-test-docker-${{ matrix.test }}
          path: /tmp/logs